require 'spec_helper'
require 'open-uri'

describe 'yandex example file spec' do
  let(:logger) { Logger.new(STDOUT).tap{|l| l.level = (ENV["DEBUG"] ? Logger::DEBUG : Logger::ERROR) } }
  let(:path)   { File.expand_path("files/yandex.xml", File.dirname(__FILE__)) }
  let(:file)   { YandexML::File.new(open(path), logger)  }

  specify do
    expect{ file.elements.each(&:attributes) }.to_not raise_error
    yml_shop = file.shop

    expect(yml_shop.categories).to be_valid

    file.offers.each { |offer| expect{ yml_shop.categories.path_to(offer.category_id) }.to_not raise_error }

    expect(yml_shop.name).to eq("Magazin")
    expect(yml_shop.company).to eq("Magazin")
    expect(yml_shop.url).to eq("http://www.magazin.ru/")

    currencies = yml_shop.currencies

    expect(currencies.count).to eq(1)
    expect(currencies.first.id).to eq("RUR")
    expect(currencies.first.rate).to eq("1")
    expect(currencies.first.plus).to eq("0")

    categories = yml_shop.categories

    expect(categories.keys).to eq([
      "1",
      "10",
      "100",
      "101",
      "2",
      "11",
      "12",
      "3",
      "13",
      "14",
      "15",
      "16",
      "4",
      "17",
      "18",
      "5",
      "19",
      "20",
      "6"
    ])

    expect(categories["1"].id).to eq("1")
    expect(categories["1"].name).to eq("Оргтехника")
    expect(categories["1"].parent_id).to eq(nil)

    expect(categories["10"].id).to eq("10")
    expect(categories["10"].name).to eq("Принтеры")
    expect(categories["10"].parent_id).to eq("1")

    expect(categories["100"].id).to eq("100")
    expect(categories["100"].name).to eq("Струйные принтеры")
    expect(categories["100"].parent_id).to eq("10")

    expect(categories["101"].id).to eq("101")
    expect(categories["101"].name).to eq("Лазерные принтеры")
    expect(categories["101"].parent_id).to eq("10")

    expect(categories["2"].id).to eq("2")
    expect(categories["2"].name).to eq("Фототехника")
    expect(categories["2"].parent_id).to eq(nil)

    expect(categories["11"].id).to eq("11")
    expect(categories["11"].name).to eq("Фотоаппараты")
    expect(categories["11"].parent_id).to eq("2")

    expect(categories["12"].id).to eq("12")
    expect(categories["12"].name).to eq("Объективы")
    expect(categories["12"].parent_id).to eq("2")

    expect(categories["3"].id).to eq("3")
    expect(categories["3"].name).to eq("Книги")
    expect(categories["3"].parent_id).to eq(nil)

    expect(categories["13"].id).to eq("13")
    expect(categories["13"].name).to eq("Детективы")
    expect(categories["13"].parent_id).to eq("3")

    expect(categories["14"].id).to eq("14")
    expect(categories["14"].name).to eq("Художественная литература")
    expect(categories["14"].parent_id).to eq("3")

    expect(categories["15"].id).to eq("15")
    expect(categories["15"].name).to eq("Учебная литература")
    expect(categories["15"].parent_id).to eq("3")

    expect(categories["16"].id).to eq("16")
    expect(categories["16"].name).to eq("Детская литература")
    expect(categories["16"].parent_id).to eq("3")

    expect(categories["4"].id).to eq("4")
    expect(categories["4"].name).to eq("Музыка и видеофильмы")
    expect(categories["4"].parent_id).to eq(nil)

    expect(categories["17"].id).to eq("17")
    expect(categories["17"].name).to eq("Музыка")
    expect(categories["17"].parent_id).to eq("4")

    expect(categories["18"].id).to eq("18")
    expect(categories["18"].name).to eq("Видеофильмы")
    expect(categories["18"].parent_id).to eq("4")

    expect(categories["5"].id).to eq("5")
    expect(categories["5"].name).to eq("Путешествия")
    expect(categories["5"].parent_id).to eq(nil)

    expect(categories["19"].id).to eq("19")
    expect(categories["19"].name).to eq("Туры")
    expect(categories["19"].parent_id).to eq("5")

    expect(categories["20"].id).to eq("20")
    expect(categories["20"].name).to eq("Авиабилеты")
    expect(categories["20"].parent_id).to eq("5")

    expect(categories["6"].id).to eq("6")
    expect(categories["6"].name).to eq("Билеты на мероприятия")
    expect(categories["6"].parent_id).to eq(nil)

    expect(yml_shop.local_delivery_cost).to eq("300")

    offers = file.offers.to_a

    expect(offers.size).to eq(7)
    expect(file.offers.to_a.size).to eq(7)

    expect(offers[0].id).to eq("12341")
    expect(offers[0].name).to eq(nil)
    expect(offers[0].type).to eq("vendor.model")
    expect(offers[0].bid).to eq("13")
    expect(offers[0].cbid).to eq("20")
    expect(offers[0].available).to eq("true")
    expect(offers[0].url).to eq("http://magazin.ru/product_page.asp?pid=14344")
    expect(offers[0].price).to eq("15000")
    expect(offers[0].oldprice).to eq(nil)
    expect(offers[0].currency_id).to eq("RUR")
    expect(offers[0].category_id.value).to eq("101")
    expect(offers[0].category_id.type).to eq("Own")
    expect(offers[0].market_category).to eq(nil)
    expect(offers[0].picture).to eq("http://magazin.ru/img/device14344.jpg")
    expect(offers[0].store).to eq(nil)
    expect(offers[0].pickup).to eq(nil)
    expect(offers[0].delivery).to eq(true)
    expect(offers[0].local_delivery_cost).to eq("300")
    expect(offers[0].delivery_options).to be_empty
    expect(offers[0].vendor).to eq("НP")
    expect(offers[0].vendor_code).to eq("Q7533A")
    expect(offers[0].description).to eq("A4, 64Mb, 600x600 dpi, USB 2.0, 29стр/мин ч/б / 15стр/мин цв, лотки на 100л и 250л, плотность до 175г/м, до 60000 стр/месяц ")
    expect(offers[0].sales_notes).to eq(nil)
    expect(offers[0].manufacturer_warranty).to eq(true)
    expect(offers[0].country_of_origin).to eq("Япония")
    expect(offers[0].ages).to be_empty
    expect(offers[0].barcodes).to be_empty
    expect(offers[0].cpa).to eq(nil)
    expect(offers[0].params).to be_empty
    expect(offers[0].type_prefix).to eq("Принтер")
    expect(offers[0].model).to eq("Color LaserJet 3000")
    expect(offers[0].author).to eq(nil)
    expect(offers[0].publisher).to eq(nil)
    expect(offers[0].series).to eq(nil)
    expect(offers[0].year).to eq(nil)
    expect(offers[0].isbn).to eq(nil)
    expect(offers[0].part).to eq(nil)
    expect(offers[0].volume).to eq(nil)
    expect(offers[0].language).to eq(nil)
    expect(offers[0].binding).to eq(nil)
    expect(offers[0].page_extent).to eq(nil)
    expect(offers[0].downloadable).to eq(nil)
    expect(offers[0].performed_by).to eq(nil)
    expect(offers[0].performance_type).to eq(nil)
    expect(offers[0].storage).to eq(nil)
    expect(offers[0].format).to eq(nil)
    expect(offers[0].recording_length).to eq(nil)
    expect(offers[0].artist).to eq(nil)
    expect(offers[0].title).to eq(nil)
    expect(offers[0].media).to eq(nil)
    expect(offers[0].starring).to eq(nil)
    expect(offers[0].director).to eq(nil)
    expect(offers[0].original_name).to eq(nil)
    expect(offers[0].country).to eq(nil)
    expect(offers[0].world_region).to eq(nil)
    expect(offers[0].region).to eq(nil)
    expect(offers[0].days).to eq(nil)
    expect(offers[0].data_tour).to eq(nil)
    expect(offers[0].hotel_stars).to eq(nil)
    expect(offers[0].room).to eq(nil)
    expect(offers[0].meal).to eq(nil)
    expect(offers[0].included).to eq(nil)
    expect(offers[0].transport).to eq(nil)
    expect(offers[0].place).to eq(nil)
    expect(offers[0].plan).to eq(nil)
    expect(offers[0].hall).to eq(nil)
    expect(offers[0].hall_part).to eq(nil)
    expect(offers[0].date).to eq(nil)
    expect(offers[0].is_premiere).to eq(nil)
    expect(offers[0].is_kids).to eq(nil)


    expect(offers[1].id).to eq("12342")
    expect(offers[1].name).to eq("Все не так. В 2 томах. Том 1")
    expect(offers[1].type).to eq("book")
    expect(offers[1].bid).to eq("17")
    expect(offers[1].cbid).to eq(nil)
    expect(offers[1].available).to eq("true")
    expect(offers[1].url).to eq("http://magazin.ru/product_page.asp?pid=14345")
    expect(offers[1].price).to eq("100")
    expect(offers[1].oldprice).to eq(nil)
    expect(offers[1].currency_id).to eq("RUR")
    expect(offers[1].category_id.value).to eq("13")
    expect(offers[1].category_id.type).to eq("Own")
    expect(offers[1].market_category).to eq(nil)
    expect(offers[1].picture).to eq("http://magazin.ru/img/book14345.jpg")
    expect(offers[1].store).to eq(nil)
    expect(offers[1].pickup).to eq(nil)
    expect(offers[1].delivery).to eq(true)
    expect(offers[1].local_delivery_cost).to eq("300")
    expect(offers[1].delivery_options).to be_empty
    expect(offers[1].vendor).to eq(nil)
    expect(offers[1].vendor_code).to eq(nil)
    expect(offers[1].description).to eq("Все прекрасно в большом патриархальном семействе Руденко. Но — увы! — впечатление это обманчиво: каждого из многочисленных представителей семьи обуревают свои потаенные страсти и запретные желания.")
    expect(offers[1].sales_notes).to eq(nil)
    expect(offers[1].manufacturer_warranty).to eq(nil)
    expect(offers[1].country_of_origin).to eq(nil)
    expect(offers[1].ages).to be_empty
    expect(offers[1].barcodes).to be_empty
    expect(offers[1].cpa).to eq(nil)
    expect(offers[1].params).to be_empty
    expect(offers[1].type_prefix).to eq(nil)
    expect(offers[1].model).to eq(nil)
    expect(offers[1].author).to eq("Александра Маринина")
    expect(offers[1].publisher).to eq("ЭКСМО - Пресс")
    expect(offers[1].series).to eq("А. Маринина - королева детектива")
    expect(offers[1].year).to eq("2009")
    expect(offers[1].isbn).to eq("978-5-699-23647-3")
    expect(offers[1].part).to eq("1")
    expect(offers[1].volume).to eq("2")
    expect(offers[1].language).to eq("rus")
    expect(offers[1].binding).to eq("70x90/32")
    expect(offers[1].page_extent).to eq("288")
    expect(offers[1].downloadable).to eq("false")
    expect(offers[1].performed_by).to eq(nil)
    expect(offers[1].performance_type).to eq(nil)
    expect(offers[1].storage).to eq(nil)
    expect(offers[1].format).to eq(nil)
    expect(offers[1].recording_length).to eq(nil)
    expect(offers[1].artist).to eq(nil)
    expect(offers[1].title).to eq(nil)
    expect(offers[1].media).to eq(nil)
    expect(offers[1].starring).to eq(nil)
    expect(offers[1].director).to eq(nil)
    expect(offers[1].original_name).to eq(nil)
    expect(offers[1].country).to eq(nil)
    expect(offers[1].world_region).to eq(nil)
    expect(offers[1].region).to eq(nil)
    expect(offers[1].days).to eq(nil)
    expect(offers[1].data_tour).to eq(nil)
    expect(offers[1].hotel_stars).to eq(nil)
    expect(offers[1].room).to eq(nil)
    expect(offers[1].meal).to eq(nil)
    expect(offers[1].included).to eq(nil)
    expect(offers[1].transport).to eq(nil)
    expect(offers[1].place).to eq(nil)
    expect(offers[1].plan).to eq(nil)
    expect(offers[1].hall).to eq(nil)
    expect(offers[1].hall_part).to eq(nil)
    expect(offers[1].date).to eq(nil)
    expect(offers[1].is_premiere).to eq(nil)
    expect(offers[1].is_kids).to eq(nil)

    expect(offers[2].id).to eq("12343")
    expect(offers[2].name).to eq("Иваnов и Rабинович, или Аj'гоу ту 'Хаjфа!")
    expect(offers[2].type).to eq("audiobook")
    expect(offers[2].bid).to eq("17")
    expect(offers[2].cbid).to eq(nil)
    expect(offers[2].available).to eq("true")
    expect(offers[2].url).to eq("http://magazin.ru/product_page.asp?pid=14346")
    expect(offers[2].price).to eq("200")
    expect(offers[2].oldprice).to eq(nil)
    expect(offers[2].currency_id).to eq("RUR")
    expect(offers[2].category_id.value).to eq("14")
    expect(offers[2].category_id.type).to eq("Own")
    expect(offers[2].market_category).to eq(nil)
    expect(offers[2].picture).to eq("http://magazin.ru/img/book14346.jpg")
    expect(offers[2].store).to eq(nil)
    expect(offers[2].pickup).to eq(nil)
    expect(offers[2].delivery).to eq(nil)
    expect(offers[2].local_delivery_cost).to eq(nil)
    expect(offers[2].delivery_options).to be_empty
    expect(offers[2].vendor).to eq(nil)
    expect(offers[2].vendor_code).to eq(nil)
    expect(offers[2].description).to eq("Перу Владимира Кунина принадлежат десятки сценариев к кинофильмам, серия книг про КЫСЮ и многое, многое другое.")
    expect(offers[2].sales_notes).to eq(nil)
    expect(offers[2].manufacturer_warranty).to eq(nil)
    expect(offers[2].country_of_origin).to eq(nil)
    expect(offers[2].ages).to be_empty
    expect(offers[2].barcodes).to be_empty
    expect(offers[2].cpa).to eq(nil)
    expect(offers[2].params).to be_empty
    expect(offers[2].type_prefix).to eq(nil)
    expect(offers[2].model).to eq(nil)
    expect(offers[2].author).to eq("Владимир Кунин")
    expect(offers[2].publisher).to eq("1С-Паблишинг, Союз")
    expect(offers[2].series).to eq(nil)
    expect(offers[2].year).to eq("2009")
    expect(offers[2].isbn).to eq("978-5-9677-0757-5")
    expect(offers[2].part).to eq(nil)
    expect(offers[2].volume).to eq(nil)
    expect(offers[2].language).to eq("ru")
    expect(offers[2].binding).to eq(nil)
    expect(offers[2].page_extent).to eq(nil)
    expect(offers[2].downloadable).to eq("true")
    expect(offers[2].performed_by).to eq("Николай Фоменко")
    expect(offers[2].performance_type).to eq("начитана")
    expect(offers[2].storage).to eq("CD")
    expect(offers[2].format).to eq("mp3")
    expect(offers[2].recording_length).to eq("45m23s")
    expect(offers[2].artist).to eq(nil)
    expect(offers[2].title).to eq(nil)
    expect(offers[2].media).to eq(nil)
    expect(offers[2].starring).to eq(nil)
    expect(offers[2].director).to eq(nil)
    expect(offers[2].original_name).to eq(nil)
    expect(offers[2].country).to eq(nil)
    expect(offers[2].world_region).to eq(nil)
    expect(offers[2].region).to eq(nil)
    expect(offers[2].days).to eq(nil)
    expect(offers[2].data_tour).to eq(nil)
    expect(offers[2].hotel_stars).to eq(nil)
    expect(offers[2].room).to eq(nil)
    expect(offers[2].meal).to eq(nil)
    expect(offers[2].included).to eq(nil)
    expect(offers[2].transport).to eq(nil)
    expect(offers[2].place).to eq(nil)
    expect(offers[2].plan).to eq(nil)
    expect(offers[2].hall).to eq(nil)
    expect(offers[2].hall_part).to eq(nil)
    expect(offers[2].date).to eq(nil)
    expect(offers[2].is_premiere).to eq(nil)
    expect(offers[2].is_kids).to eq(nil)

    expect(offers[3].id).to eq("12344")
    expect(offers[3].name).to eq(nil)
    expect(offers[3].type).to eq("artist.title")
    expect(offers[3].bid).to eq("11")
    expect(offers[3].cbid).to eq(nil)
    expect(offers[3].available).to eq("true")
    expect(offers[3].url).to eq("http://magazin.ru/product_page.asp?pid=14347")
    expect(offers[3].price).to eq("450")
    expect(offers[3].oldprice).to eq(nil)
    expect(offers[3].currency_id).to eq("RUR")
    expect(offers[3].category_id.value).to eq("17")
    expect(offers[3].category_id.type).to eq("Own")
    expect(offers[3].market_category).to eq(nil)
    expect(offers[3].picture).to eq("http://magazin.ru/img/cd14347.jpg")
    expect(offers[3].store).to eq(nil)
    expect(offers[3].pickup).to eq(nil)
    expect(offers[3].delivery).to eq(true)
    expect(offers[3].local_delivery_cost).to eq(nil)
    expect(offers[3].delivery_options).to be_empty
    expect(offers[3].vendor).to eq(nil)
    expect(offers[3].vendor_code).to eq(nil)
    expect(offers[3].description).to eq(" Dark Side Of The Moon, поставивший мир на уши невиданным сочетанием звуков, — это всего-навсего девять треков, и даже не все они писались специально для альбома. Порывшись по сусекам, участники Pink Floyd мудро сделали новое из хорошо забытого старого — песен, которые почему-либо не пошли в дело или остались незаконченными. Одним из источников вдохновения стали саундтреки для кинофильмов, которые группа производила в больших количествах.")
    expect(offers[3].sales_notes).to eq(nil)
    expect(offers[3].manufacturer_warranty).to eq(nil)
    expect(offers[3].country_of_origin).to eq(nil)
    expect(offers[3].ages).to be_empty
    expect(offers[3].barcodes).to be_empty
    expect(offers[3].cpa).to eq(nil)
    expect(offers[3].params).to be_empty
    expect(offers[3].type_prefix).to eq(nil)
    expect(offers[3].model).to eq(nil)
    expect(offers[3].author).to eq(nil)
    expect(offers[3].publisher).to eq(nil)
    expect(offers[3].series).to eq(nil)
    expect(offers[3].year).to eq("1999")
    expect(offers[3].isbn).to eq(nil)
    expect(offers[3].part).to eq(nil)
    expect(offers[3].volume).to eq(nil)
    expect(offers[3].language).to eq(nil)
    expect(offers[3].binding).to eq(nil)
    expect(offers[3].page_extent).to eq(nil)
    expect(offers[3].downloadable).to eq(nil)
    expect(offers[3].performed_by).to eq(nil)
    expect(offers[3].performance_type).to eq(nil)
    expect(offers[3].storage).to eq(nil)
    expect(offers[3].format).to eq(nil)
    expect(offers[3].recording_length).to eq(nil)
    expect(offers[3].artist).to eq("Pink Floyd")
    expect(offers[3].title).to eq("Dark Side Of The Moon, Platinum Disc")
    expect(offers[3].media).to eq("CD")
    expect(offers[3].starring).to eq(nil)
    expect(offers[3].director).to eq(nil)
    expect(offers[3].original_name).to eq(nil)
    expect(offers[3].country).to eq(nil)
    expect(offers[3].world_region).to eq(nil)
    expect(offers[3].region).to eq(nil)
    expect(offers[3].days).to eq(nil)
    expect(offers[3].data_tour).to eq(nil)
    expect(offers[3].hotel_stars).to eq(nil)
    expect(offers[3].room).to eq(nil)
    expect(offers[3].meal).to eq(nil)
    expect(offers[3].included).to eq(nil)
    expect(offers[3].transport).to eq(nil)
    expect(offers[3].place).to eq(nil)
    expect(offers[3].plan).to eq(nil)
    expect(offers[3].hall).to eq(nil)
    expect(offers[3].hall_part).to eq(nil)
    expect(offers[3].date).to eq(nil)
    expect(offers[3].is_premiere).to eq(nil)
    expect(offers[3].is_kids).to eq(nil)

    expect(offers[4].id).to eq("12345")
    expect(offers[4].name).to eq(nil)
    expect(offers[4].type).to eq("artist.title")
    expect(offers[4].bid).to eq("56")
    expect(offers[4].cbid).to eq(nil)
    expect(offers[4].available).to eq("true")
    expect(offers[4].url).to eq("http://magazin.ru/product_page.asp?pid=14348")
    expect(offers[4].price).to eq("400")
    expect(offers[4].oldprice).to eq(nil)
    expect(offers[4].currency_id).to eq("RUR")
    expect(offers[4].category_id.value).to eq("18")
    expect(offers[4].category_id.type).to eq("Own")
    expect(offers[4].market_category).to eq(nil)
    expect(offers[4].picture).to eq("http://magazin.ru/img/dvd14348.jpg")
    expect(offers[4].store).to eq(nil)
    expect(offers[4].pickup).to eq(nil)
    expect(offers[4].delivery).to eq(true)
    expect(offers[4].local_delivery_cost).to eq(nil)
    expect(offers[4].delivery_options).to be_empty
    expect(offers[4].vendor).to eq(nil)
    expect(offers[4].vendor_code).to eq(nil)
    expect(offers[4].description).to eq("Гадкий утенок из провинциального городка покидает свое гнездо, и в компании своей подруги отправляется искать веселой жизни в большой и загадочный город. Фильм о мечтах и реальности, дружбе и юности молодой девушки, приключения которой повторяют судьбы Золушки и героини Джулии Робертс из ставшего классикой фильма Красотка...")
    expect(offers[4].sales_notes).to eq(nil)
    expect(offers[4].manufacturer_warranty).to eq(nil)
    expect(offers[4].country_of_origin).to eq(nil)
    expect(offers[4].ages).to be_empty
    expect(offers[4].barcodes).to be_empty
    expect(offers[4].cpa).to eq(nil)
    expect(offers[4].params).to be_empty
    expect(offers[4].type_prefix).to eq(nil)
    expect(offers[4].model).to eq(nil)
    expect(offers[4].author).to eq(nil)
    expect(offers[4].publisher).to eq(nil)
    expect(offers[4].series).to eq(nil)
    expect(offers[4].year).to eq("1999")
    expect(offers[4].isbn).to eq(nil)
    expect(offers[4].part).to eq(nil)
    expect(offers[4].volume).to eq(nil)
    expect(offers[4].language).to eq(nil)
    expect(offers[4].binding).to eq(nil)
    expect(offers[4].page_extent).to eq(nil)
    expect(offers[4].downloadable).to eq(nil)
    expect(offers[4].performed_by).to eq(nil)
    expect(offers[4].performance_type).to eq(nil)
    expect(offers[4].storage).to eq(nil)
    expect(offers[4].format).to eq(nil)
    expect(offers[4].recording_length).to eq(nil)
    expect(offers[4].artist).to eq(nil)
    expect(offers[4].title).to eq("Свадьба Мюриэл")
    expect(offers[4].media).to eq("DVD")
    expect(offers[4].starring).to eq("Тони Колетт (Toni Collette), Рэйчел Грифитс (Rachel Griffiths)")
    expect(offers[4].director).to eq("П Дж Хоген")
    expect(offers[4].original_name).to eq("Muriel's wedding")
    expect(offers[4].country).to eq("Австралия")
    expect(offers[4].world_region).to eq(nil)
    expect(offers[4].region).to eq(nil)
    expect(offers[4].days).to eq(nil)
    expect(offers[4].data_tour).to eq(nil)
    expect(offers[4].hotel_stars).to eq(nil)
    expect(offers[4].room).to eq(nil)
    expect(offers[4].meal).to eq(nil)
    expect(offers[4].included).to eq(nil)
    expect(offers[4].transport).to eq(nil)
    expect(offers[4].place).to eq(nil)
    expect(offers[4].plan).to eq(nil)
    expect(offers[4].hall).to eq(nil)
    expect(offers[4].hall_part).to eq(nil)
    expect(offers[4].date).to eq(nil)
    expect(offers[4].is_premiere).to eq(nil)
    expect(offers[4].is_kids).to eq(nil)

    expect(offers[5].id).to eq("12346")
    expect(offers[5].name).to eq("Hilton")
    expect(offers[5].type).to eq("tour")
    expect(offers[5].bid).to eq("71")
    expect(offers[5].cbid).to eq(nil)
    expect(offers[5].available).to eq("true")
    expect(offers[5].url).to eq("http://magazin.ru/product_page.asp?pid=14349")
    expect(offers[5].price).to eq("30000")
    expect(offers[5].oldprice).to eq(nil)
    expect(offers[5].currency_id).to eq("RUR")
    expect(offers[5].category_id.value).to eq("19")
    expect(offers[5].category_id.type).to eq("Own")
    expect(offers[5].market_category).to eq(nil)
    expect(offers[5].picture).to eq("http://magazin.ru/img/travel14349.jpg")
    expect(offers[5].store).to eq(nil)
    expect(offers[5].pickup).to eq(nil)
    expect(offers[5].delivery).to eq(false)
    expect(offers[5].local_delivery_cost).to eq("300")
    expect(offers[5].delivery_options).to be_empty
    expect(offers[5].vendor).to eq(nil)
    expect(offers[5].vendor_code).to eq(nil)
    expect(offers[5].description).to eq("Отдых в Египте.")
    expect(offers[5].sales_notes).to eq(nil)
    expect(offers[5].manufacturer_warranty).to eq(nil)
    expect(offers[5].country_of_origin).to eq(nil)
    expect(offers[5].ages).to be_empty
    expect(offers[5].barcodes).to be_empty
    expect(offers[5].cpa).to eq(nil)
    expect(offers[5].params).to be_empty
    expect(offers[5].type_prefix).to eq(nil)
    expect(offers[5].model).to eq(nil)
    expect(offers[5].author).to eq(nil)
    expect(offers[5].publisher).to eq(nil)
    expect(offers[5].series).to eq(nil)
    expect(offers[5].year).to eq(nil)
    expect(offers[5].isbn).to eq(nil)
    expect(offers[5].part).to eq(nil)
    expect(offers[5].volume).to eq(nil)
    expect(offers[5].language).to eq(nil)
    expect(offers[5].binding).to eq(nil)
    expect(offers[5].page_extent).to eq(nil)
    expect(offers[5].downloadable).to eq(nil)
    expect(offers[5].performed_by).to eq(nil)
    expect(offers[5].performance_type).to eq(nil)
    expect(offers[5].storage).to eq(nil)
    expect(offers[5].format).to eq(nil)
    expect(offers[5].recording_length).to eq(nil)
    expect(offers[5].artist).to eq(nil)
    expect(offers[5].title).to eq(nil)
    expect(offers[5].media).to eq(nil)
    expect(offers[5].starring).to eq(nil)
    expect(offers[5].director).to eq(nil)
    expect(offers[5].original_name).to eq(nil)
    expect(offers[5].country).to eq("Египет")
    expect(offers[5].world_region).to eq("Африка")
    expect(offers[5].region).to eq("Хургада")
    expect(offers[5].days).to eq("7")
    expect(offers[5].data_tour).to eq("08/06/2014")
    expect(offers[5].hotel_stars).to eq("5*****")
    expect(offers[5].room).to eq("SNG")
    expect(offers[5].meal).to eq("ALL")
    expect(offers[5].included).to eq("авиаперелет, трансфер, проживание, питание, страховка")
    expect(offers[5].transport).to eq("Авиа")
    expect(offers[5].place).to eq(nil)
    expect(offers[5].plan).to eq(nil)
    expect(offers[5].hall).to eq(nil)
    expect(offers[5].hall_part).to eq(nil)
    expect(offers[5].date).to eq(nil)
    expect(offers[5].is_premiere).to eq(nil)
    expect(offers[5].is_kids).to eq(nil)

    expect(offers[6].id).to eq("12347")
    expect(offers[6].name).to eq("Дмитрий Хворостовский и Национальный филармонический оркестр России. Дирижер — Владимир Спиваков.")
    expect(offers[6].type).to eq("event-ticket")
    expect(offers[6].bid).to eq("13")
    expect(offers[6].cbid).to eq(nil)
    expect(offers[6].available).to eq("true")
    expect(offers[6].url).to eq("http://magazin.ru/product_page.asp?pid=14350")
    expect(offers[6].price).to eq("5000")
    expect(offers[6].oldprice).to eq(nil)
    expect(offers[6].currency_id).to eq("RUR")
    expect(offers[6].category_id.value).to eq("6")
    expect(offers[6].category_id.type).to eq("Own")
    expect(offers[6].market_category).to eq(nil)
    expect(offers[6].picture).to eq("http://magazin.ru/img/tickets14350.jpg")
    expect(offers[6].store).to eq(nil)
    expect(offers[6].pickup).to eq(nil)
    expect(offers[6].delivery).to eq(true)
    expect(offers[6].local_delivery_cost).to eq("300")
    expect(offers[6].delivery_options).to be_empty
    expect(offers[6].vendor).to eq(nil)
    expect(offers[6].vendor_code).to eq(nil)
    expect(offers[6].description).to eq("Концерт Дмитрия Хворостовского и Национального филармонического оркестра России под управлением Владимира Спивакова.")
    expect(offers[6].sales_notes).to eq(nil)
    expect(offers[6].manufacturer_warranty).to eq(nil)
    expect(offers[6].country_of_origin).to eq(nil)
    expect(offers[6].ages).to be_empty
    expect(offers[6].barcodes).to be_empty
    expect(offers[6].cpa).to eq(nil)
    expect(offers[6].params).to be_empty
    expect(offers[6].type_prefix).to eq(nil)
    expect(offers[6].model).to eq(nil)
    expect(offers[6].author).to eq(nil)
    expect(offers[6].publisher).to eq(nil)
    expect(offers[6].series).to eq(nil)
    expect(offers[6].year).to eq(nil)
    expect(offers[6].isbn).to eq(nil)
    expect(offers[6].part).to eq(nil)
    expect(offers[6].volume).to eq(nil)
    expect(offers[6].language).to eq(nil)
    expect(offers[6].binding).to eq(nil)
    expect(offers[6].page_extent).to eq(nil)
    expect(offers[6].downloadable).to eq(nil)
    expect(offers[6].performed_by).to eq(nil)
    expect(offers[6].performance_type).to eq(nil)
    expect(offers[6].storage).to eq(nil)
    expect(offers[6].format).to eq(nil)
    expect(offers[6].recording_length).to eq(nil)
    expect(offers[6].artist).to eq(nil)
    expect(offers[6].title).to eq(nil)
    expect(offers[6].media).to eq(nil)
    expect(offers[6].starring).to eq(nil)
    expect(offers[6].director).to eq(nil)
    expect(offers[6].original_name).to eq(nil)
    expect(offers[6].country).to eq(nil)
    expect(offers[6].world_region).to eq(nil)
    expect(offers[6].region).to eq(nil)
    expect(offers[6].days).to eq(nil)
    expect(offers[6].data_tour).to eq(nil)
    expect(offers[6].hotel_stars).to eq(nil)
    expect(offers[6].room).to eq(nil)
    expect(offers[6].meal).to eq(nil)
    expect(offers[6].included).to eq(nil)
    expect(offers[6].transport).to eq(nil)
    expect(offers[6].place).to eq("Московский международный Дом музыки")
    expect(offers[6].plan).to eq("http://magazin.ru/img/mmdm_plan.jpg")
    expect(offers[6].hall).to eq("Большой зал")
    expect(offers[6].hall_part).to eq("Партер р. 1-5")
    expect(offers[6].date).to eq("2014-12-31T19:00")
    expect(offers[6].is_premiere).to eq("0")
    expect(offers[6].is_kids).to eq("0")
  end
end
